- name: Clone Cassandra repository
  git: repo=http://git-wip-us.apache.org/repos/asf/cassandra.git dest="{{cstar_source_location}}/cassandra"

- name: Install ant
  sudo: yes
  action: apt pkg={{item}} state=present
  with_items:
    - ant
    - ant-optional
