- name: Install Java prereq
  sudo: yes
  apt: pkg=software-properties-common state=present

- name: Add webupd8team Java repository and update apt cache
  apt_repository: repo='ppa:webupd8team/java'
  sudo: yes

- name: Automatically accept Oracle license # via https://github.com/vrischmann/ansible-role-java/
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
  sudo: yes
  changed_when: false

- name: Install Oracle installer
  apt: pkg=oracle-java7-installer
  sudo: yes

- name: Install ant
  sudo: yes
  action: apt pkg={{item}} state=present
  with_items:
    - ant
    - ant-optional
